version: "3"

services:
  client: 
    build: "./client"
    container_name: client-react
    ports:
      - 3000:3000
    volumes:
      - "./client:/usr/app"
      - "/usr/app/node_modules"
    environment:
      - CHOKIDAR_USEPOLLING=true
  server: 
      # image: "becodeorg/php"
      build: "./server/"
      container_name: server-php
      volumes: 
        - "./server/src:/var/www/html"
      ports: 
        - "80:80"